### PR TITLE
feat(admin-maps): replace 'Quick Edit' with 'Preview Map' in list table #25

### PR DESCRIPTION
**Pull request by nishitlangaliya**
## Description
This PR will fix https://github.com/WordImpress/Google-Maps-Builder/issues/25
Necessary js function and changes added.

## How Has This Been Tested?
Manually tested

## Video 
https://www.useloom.com/share/c5b9145d3f9a46178d2cca9a03db5290

## Types of changes
New feature (non-breaking change which adds functionality) 

## Checklist:
- [X] My code is tested.
- [X] My code follows the WordPress code style.
- [X] My code follows has proper inline documentation.

### CODE REVIEW

**Comment by DevinWalker** [comment]
@nishitlangaliya can you resolve the conflict here?

**Comment by DevinWalker** [comment]
@nishitlangaliya looks like the conflict is back. Can you resolve that for me?

**Comment by nishitlangaliya** [comment]
@DevinWalker ,

I have resolved the conflicts would you please check for the same and let me know if still any issue.

Thanks

**Comment by nishitlangaliya** [comment]
@DevinWalker , I am closing this PR as this issue is merged now on https://github.com/WordImpress/Maps-Builder-Core/pull/59 
Thanks

**Pull request closed without merging**
